### PR TITLE
fix database field rename and use datetime.now() instead of timezone.now()

### PR DESCRIPTION
**Pull request by Astranox**
fix auto-deletion of expired users.

### CODE REVIEW

**Comment by mathiasertl** [comment]
The fix in core/admin is a no-brainer. But why not use timezone.now()?

**Comment by mathiasertl** [comment]
Also: the queryset filtering for `created` should yield a traceback and fail. And we should get emails for that. Why don't we?

**Comment by Astranox** [comment]
tracebacks went to a different email-account, but it failed on timezone.now() first, as it didn't find the timezone module at all

**Comment by Astranox** [comment]
also everywhere else datetime.now() is used

**Comment by cdroege** [comment]
The cleanup command throws an exception with the current version in master, because of that:

```
[...]
File "[...]django-xmpp-account/core/management/commands/cleanup.py", line 78, in handle
created_before = timezone.now() - _default_timeout_delta
NameError: name 'timezone' is not defined
```

**Comment by mathiasertl** [comment]
@Astranox 

The timezone issue was due to a missing import, not a typo. I did my own commit to fix the issue correctly.

**Pull request closed without merging**
